### PR TITLE
Make `inverse(::VectorTransfrom, x)` return a vector of floats

### LINKED ISSUE #132: Avoid that `inverse(::VectorTransform, x)` returns a `Vector{Union{}}`?
In generic code, it's very convenient to use `inverse(::VectorTransform, x)` (or in my case mainly `inverse(::TransformTuple, x::NamedTuple)`). In my application we also allow users to fix certain parameters during inference by internally replacing their transforms with `Constant` transforms. This works nicely.

However, users may actually fix all population parameters (and only perform inference of individual parameters), which implies that all transforms in the `TransformTuple` of population parameters are `Constant`s. Unfortunately, in this case `inverse` with the `TransformTuple` returns a `Vector{Union{}}` instead of e.g. a `Vector{Float64}` or `Vector{Int}`, but support for `Vector{Union{}}` in downstream applications is much more limited, compare e.g.

```julia
julia> sum(Float64[])
0.0

julia> sum(Union{}[])
ERROR: ArgumentError: reducing over an empty collection is not allowed; consider supplying `init` to the reducer
...

julia> mean(Float64[])
NaN

julia> mean(Union{}[])
ERROR: ArgumentError: reducing over an empty collection is not allowed; consider supplying `init` to the reducer
...

julia> std(Float64[])
NaN

julia> std(Union{}[])
ERROR: ArgumentError: reducing over an empty collection is not allowed; consider supplying `init` to the reducer
...
```

Therefore, I switched to a custom
```julia
function _no_bottom_inverse(trf::TransformVariables.VectorTransform, x)
  T = TransformVariables.inverse_eltype(trf, x)
  if T === Union{}
    T = Float64
  end
  return TransformVariables.inverse!(
    Vector{T}(undef, TransformVariables.dimension(trf)),
    trf,
    x,
  )
end
```
but I'm somewhat unhappy because a) it requires that all calls of `inverse` are replaced with `_no_bottom_inverse` (which seems easy to break in future PRs) and b) it seems like a problem that might be useful to solve upstream.

IMO an array with non-numerical element type is never desirable, so maybe the implementation of `inverse(::VectorTransform, x)` should already handle this case, similar to `_no_bottom_inverse`? Maybe one should go even further and make it return `float(T)`?
I also wonder if it should be handled on the level of `inverse_eltype(::VectorTransform, x)` (which was not really an option in my downstream code).

(IMO `inverse_eltype(::Constant)` should not be changed - I think `Union{}` is the right choice there, it avoids unnecessary promotions which might be relevant for e.g. operations with `Float32`.)

### PR DESCRIPTION
**Pull request by devmotion**
Fixes #132.

I was debating with myself whether this should be addressed in `inverse` or `inverse_eltype`. I came to the conclusion that `inverse` is the right place because modifications in `inverse_eltype` could lead to undesired results (too early change to floats or `Float64`) when composing vector transforms (and the current `inverse_eltype` definitions are not actually incorrect).

### CODE REVIEW

File: src/generic.jl [hunk 1]
```diff
@@ -266,8 +266,17 @@ function transform_and_logjac(t::VectorTransform, x::AbstractVector)
     y, ℓ
 end
 
+# We want to avoid vectors with non-numerical element types
+# Ref https://github.com/tpapp/TransformVariables.jl/issues/132
 function inverse(t::VectorTransform, y)
-    inverse!(Vector{inverse_eltype(t, y)}(undef, dimension(t)), t, y)
+    inverse!(Vector{_float_or_Float64(inverse_eltype(t, y))}(undef, dimension(t)), t, y)
```
Comment (tpapp) [inline src/generic.jl:272]: I think that this catches too much. I would simply condition on `dimension(t) == 0`, I don't think that `Union{}` can happen outside that. Something like

```julia
T = inverse_eltype(t, y)
d = dimension(t)    
if T === Union{} || d == 0
    T = Float64
end
inverse!(Vector{T)}(undef, d), t, y)
```

Comment (devmotion) [reply src/generic.jl:272]: In your suggestion you seem to condition on `Union{}` as well?

I was actually considering checking only `dimsnion(t) == 0` as for my use case it shouldn't matter. I went with checking only whether `inverse_eltype(t, y) === Union{}` since I was worried that branching on the value of `dimension(t)` could introduce a type instability.

Comment (tpapp) [reply src/generic.jl:272]: Yes, that makes sense.

But now that I think about it, it is kind of funny to make `eltype(inverse(t, y)) != inverse_eltype(t, y)`. I think it would be best to fix it in `inverse_eltype`, the following way:

1. Introduce a function, eg `narrow_inverse_eltype`, basically rename `inverse_eltype` to that, in the state before this PR. Document that types should extent it.

2. In `inverse_eltype`, just check for `Union{}` and replace with `Float64`.

Now that I look at the code, the eltype determination is a bit flaky in a lot of places:

```julia
julia> t = as(Array, 3)
[1:3] 3×
  asℝ

julia> inverse(t, Any[1, 2.1, 3])
ERROR: InexactError: Int64(2.1)
```

We should probably rethink it as a whole for all kinds of corner cases. Suggestions welcome.

Comment (devmotion) [reply src/generic.jl:272]: Initially I wanted to change `inverse_eltype`. But making it concrete seemed wrong - similar to the scalar transforms (such as `inverse_eltype(::Constant) = Union{}`), per se an `inverse_eltype` seems completely correct: It avoids prematurely introducing e.g. `Float64` in a "non-leaf" transform (ie before applying all compositions or combinations). IMO the element type is only relevant when the output array is actually instantiated, and changes (such as changing to floating point number types or turning `Union{}` to `Float64`) should only be performed at this final stage - as done in this PR.

> Now that I look at the code, the eltype determination is a bit flaky in a lot of places:

I think this example is quite special as it is caused by the same bug as https://github.com/tpapp/TransformVariables.jl/issues/73: The element type of the output (`inverse_eltype`) is in this case computed based on the first element of input `x`. Whereas actually for non-concrete element types, I think `inverse_eltype` take into account the full input `x`, e.g. by promoting the `inverse_eltype`s for each element (can't be inferred in this case) or returning an abstract type such as `Any`.

```julia
julia> TransformVariables.inverse_eltype(t, Any[1, 2.1, 3])
Int64

julia> TransformVariables.inverse_eltype(t, Any[2.1, 1, 3])
Float64
```

By construction of this failing example, it is actually fixed by this PR since `Int` would be changed to `Float64` when constructing the `Vector`. With this PR,

```julia
julia> inverse(t, Any[1, 2.1, 3])
3-element Vector{Float64}:
 1.0
 2.1
 3.0
```

**Review by tpapp — APPROVED** [review]
LGTM, thanks! I will clarify the API in another PR.

**Comment by devmotion** [comment]
Could you tag a new release? I updated the package version in this PR but you might want to also include the latest commit on the master branches with the additional explanations regarding `inverse_eltype`.

**Comment by tpapp** [comment]
I am away from my compurer for today, please tag one (I added you to the repo).

**Comment by devmotion** [comment]
OK, will do!
